### ISSUE TITLE
Question about data frame received after close

### ISSUE THREAD

**Issue by yingfangdu** [ninjasource/Ninja.WebSockets#13]
our product is this, we have a C# application using Ninja.WebSockets to send data to a browser application which is embedded in chrome.

Recently we get couple of errors from chrome side with this error message both from Windows and Mac platforms.
WebSocket connection to 'ws://localhost:49758/' failed: Data frame received after close

I checked that chrome does have a thread about this while they won't fix it.
https://bugs.chromium.org/p/chromium/issues/detail?id=372776

I want to consult check with the experts here as I see that SendAsync in this library does not check whether the WebSocket's State is open or not while other API does this check. If I add this kind of check in SendAsync, will this solve the error (Data frame received after close) we see?

**Comment by ninjasource** [comment]
Hi,

It looks like the close handshake is not being honored properly. Either on the Chrome or the Ninja websocket side. The first step is to find out who initiated the close. Open up the developer tools in chrome (F12 on windows I think) and, on the network tab, locate the websocket connection (this will usually have a status of 101 of the web socket connection is open and you can use this to see what messages are going back and forth.

You should be able to take a look at the ninja websocket logs to see if the close was initiated by it or by chrome. See Events class or search for the event source guid 7DE1A071-4F85-4DBD-8FB1-EE8D3845E087. You can use the microsoft sysinternals tool called PerfView to listen to those logs.

Once you know who initiated the close. Lets assume that Chrome closed the websocket, next thing is to find out HOW it was closed. There are two ways to terminate websocket connection properly. A fire and forget and a proper close handshake. Here is a link to the web socket spec: https://tools.ietf.org/html/rfc6455
Chrome can also just close the TCP connection. The fire and forget and TCP close are not good because the other side can happily send frames after the websocket is closed. This looks like the problem you are having. 

There are two potential ways to fix this problem:
1. Close the websocket connection from your end rather than relying on chrome to close the connection. However, it is usually the client that initiates the close but this is not a requirement. If chrome is misbehaving then I think that is a perfectly valid way of solving this problem.
2. Make sure ping pong messages are flowing between the client and server. The client (Chrome) should usually send ping messages but it it isn't then the TCP connection may be timing out and closing automatically. You can simply send ping messages from the server. Set the WebSocketServerOptions.KeepAliveInterval to something like 25 seconds.

**Comment by ninjasource** [comment]
Also, just looking at the Ninja.WebSocket SendAsync function and it doesn't check the state of the websocket before sending a frame. I would check the State before sending a data as a precaution. I should actually throw an Exception if the user attempts to send data when the websocket is already in anything but Open state.
