### ISSUE TITLE
SSL support?

### ISSUE THREAD

**Issue by manijak** [ninjasource/Ninja.WebSockets#16]
Hi,
Is there a way to enable secure websockets with this package? So that we use `wss://localhost:portnr`?

**Comment by ninjasource** [comment]
Hi Manijak,

SSL support is built into the client and is automatically enables when you use wss as you have above.

I assume that your question relates to the server. In that case, as the server, you have to complete the ssl handshake and upgrade your TCP stream to an SSL stream. This is actually out of the scope of this library because the most common way to do use something like nginx as a reverse proxy that also handles SSL and manages certificates with something like certbot and letsencrypt. However, if you want to secure the stream yourself you can do it in .net with the following example code:

```csharp
        private Stream GetStream(TcpClient tcpClient)
        {
            Stream stream = tcpClient.GetStream();

            // we have no ssl certificate
            if (_sslCertificate == null)
            {
                _logger.Information(this.GetType(), "Connection not secure");
                return stream;
            }

            try
            {
                SslStream sslStream = new SslStream(stream, false);
                _logger.Information(this.GetType(), "Attempting to secure connection...");
                sslStream.AuthenticateAsServer(_sslCertificate, false, SslProtocols.Tls, true);
                _logger.Information(this.GetType(), "Connection successfully secured");
                return sslStream;
            }
            catch (AuthenticationException e)
            {
                // TODO: send 401 Unauthorized
                throw;
            }
        }
```

where a certificate can be loaded from the file system as follows:

```csharp
        private static X509Certificate2 GetCertificate()
        {
            // it is clearly WRONG to store the certificate and password insecurely on disk like this but this is a demo
            // you would normally use the built in windows certificate store
            string certFile = Settings.Default.CertificateFile;
            if (!File.Exists(certFile))
            {
                throw new FileNotFoundException("Certificate file not found: " + certFile);
            }

            string certPassword = Settings.Default.CertificatePassword;
            var cert = new X509Certificate2(certFile, certPassword);
            _logger.Information(typeof (Program), "Successfully loaded certificate");
            return cert;
        }
```

If you are interested in hosting your .net app on nginx then this is a good read:
https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/linux-nginx?view=aspnetcore-2.2
Same idea applies to IIS on windows.

I hope this helps!

**Comment by manijak** [comment]
Thanks for the suggestion! A bit of background: We are building websocket support in a small .net desktop application that is going to broadcast only on localhost. There is no webserver or iis involved. Our web applications need to communicate with local machine hardware and we found this to be the way to do it.  
```
WebSite (browser) > websocket (wss://) > Desktop Application (.net) > Hardware (usb/network)
```
Chrome is the only one (for now) allowing for unsecure `ws://` connection to a websocket server. Firefox, Edge, and Safari do not. So we are in need of securing our server with wss:// and a self-signed certificate (that we generate in the desktop app). 

Thanks for the tip on how to secure the server connection. I am aware that your library is not mandatory for the job, it's just that I have been struggling in general to find proper examples on how to do this :)

**Comment by ninjasource** [comment]
Glad I could help. I'm surprised that Firefox does not support insecure localhost websocket connections. I thought it did! I know that if the original connection was over https then a browser would not allow an insecure websocket connection. If localhost then your original connection can be http. Really, I don't know why the browsers show a warning for insecure localhost connections, its just laziness on their part.

**Comment by manijak** [comment]
Well most browsers do support it if both the client & server are localhost. But if say the client is not, then it will not connect to a localhost websocet (except for Chrome).
