### ISSUE TITLE
Invalid pointer address in attempting to use a pointer. Possible DNS issue ?

### ISSUE THREAD

**Issue by cocapasteque** [ninjasource/Ninja.WebSockets#19]
Hello there,
I had a strange issue while trying to connect to my websocket server :

```SocketException: The system detected an invalid pointer address in attempting to use a pointer argument in a call.```

I tried to narrow down the problem and see exactly where this exception happens but no success with that. It seems related to our DNS setup (could be a wrong config on our side). 

Some context: the server is deployed in a Kubernetes node, which has a IP address. We have 3 nodes in total and a master node. 
Nginx listens on the 3 nodes and delegates the request to the appropriate service. So we have in total 4 IP addresses in the game (3 minions and 1 master). 
By talking with a colleague about my issue, we figured out that a DNS lookup on the hostname of my server returns 3 IP addresses, which should be the 3 minions but it happens to be 2 minions and 1 master. That's where we have it wrong and we will fix that, this should resolve my issue. 

But then he told me that all our browser services, that uses websockets libraries don't have this problem. Apparently if they fail, they retry on the next IP.

So my question is this one: is there any retry on fail when trying to establish a connection ? Are you even able to catch this kind of exception in the library or does it happen in the C# source and you cannot do anything about this ?

**Comment by ninjasource** [comment]
Hi,

Can you post the full stack trace so that I know where in the code it failed? There are a couple of things to try. You can use event tracing to get very detailed logs using PerfView. I don't know if event tracing works on Linux though so you may be out of luck with that line. Take a look at Events.cs to see what guid to listen to if you are using Windows.

Another thing to look for is how you are using the web socket instance. Are you accessing the same instance from multiple threads? If you are then I would imagine that the stream class could run into pointer problems under the hood.

Btw, is there any reason why you are not using .net core for the websocket server? I'm always interested to know why people are using my library as a server. I understand that people use it for the .net 4.5 compatible client.

**Comment by cocapasteque** [comment]
Hey,

We fixed the issue within our DNS and I didn't run into this issue anymore so I can't really log it anymore unfortunatly, 
But that makes me believe that the issue was what I thought in the first place.

I'll check if I still have the log file somewhere on my machine. 

I'm using Mirror websocket transport (Unity) that is built on your library :)

**Comment by ninjasource** [comment]
Oh great! Nice to know it's used in Mirror. Glad I kept it .net standard 2.0. I made a Rust version too if anyone is interested. It's in crates.io called embedded-websocket. A bit more low level to use but more actively developed.
