### ISSUE TITLE
The WebSocket implementation is not thread safe.

### ISSUE THREAD

**Issue by yingfangdu** [ninjasource/Ninja.WebSockets#3]
see WebSocketImplementation's implementation for example SendAsync

**Comment by ninjasource** [comment]
Hi Ying,

Thank you for your observation. The WebSocketImplementation class is not meant to be thread safe. This must not be confused with not being able to use it in a multithreaded environment. Of course this library is designed to be used very concurrently with many simultaneous connections. However, the WebSockImplementation class really just a private connection between a server and a client, independent of all other connections. It does not really make sense to call SendAsync from multiple threads especially since this library supports continuation frames. The idea is to have one thread for receiving and another for sending. Max two threads per unique WebSocket connection. This is the most you can get out of a full duplex tcp connection anyway.

**Comment by yingfangdu** [comment]
Thanks for the reply. I was wrong about how to send data in different threads. It turns out that I need to make sure thread safe in the caller when call SendAsync protect the data integrity to the client.

Thanks very much for your information. I will close it.
