### ISSUE TITLE
Ninja.WebSockets.dll is not a strongly named assembly.

### ISSUE THREAD

**Issue by yingfangdu** [ninjasource/Ninja.WebSockets#8]
Ninja.WebSockets.dll is not a strongly named assembly.

simply sign with a key file will solve this. Thanks very much.

![image](https://user-images.githubusercontent.com/9310605/42964034-c546bae2-8b4a-11e8-92ff-c405e4cd9adf.png)

**Comment by yingfangdu** [comment]
Hi, could you pls help us fix this issue?

**Comment by ninjasource** [comment]
Hi,
I’ve looked into this but unfortunately I’m on holidays right now so strongly typing this library isn’t going to happen until the beginning of September. Can I suggest that you clone the repository and use it as a project reference instead of a nuget binary reference. That way you won’t have to rely on strongly typed binary references for now.

**Comment by ninjasource** [comment]
The nuget package is now signed.
